intent_responses = {}

faq_knowledge_base = {
    "admission_process": "You can apply for admission online through the college portal or offline by visiting the college admission cell.",
    "ug_courses": "Govt PG College Una offers undergraduate programs such as B.A, B.Com, B.Sc, BBA, and BCA.",
    "pg_courses": "Postgraduate programs include M.A (English, Hindi, Political Science, History), M.Com, and M.Sc (Mathematics).",
    "documents_required": "Documents include 10th and 12th mark sheets, character certificate, migration certificate, passport-size photographs, and ID proof.",
    "admission_last_date": "The last date for admission is usually in July. Check the official website or notice board for updates.",
    "scholarships": "Scholarships are available under state and central government schemes for SC, ST, OBC, and EWS students.",
    "fee_structure": "The fee varies by course. UG programs cost approximately ₹3000–₹5000 per year; PG programs are slightly higher.",
    "hostel_facility": "Govt PG College Una does not offer hostel facilities. Students usually arrange private PGs nearby.",
    "college_timings": "Classes usually run from 9:00 AM to 3:00 PM, Monday to Saturday.",
    "library": "The college library has thousands of academic and reference books and also provides access to e-resources.",
    "sports_facilities": "Facilities for cricket, volleyball, kabaddi, badminton, and athletics are available on campus.",
    "placement_cell": "A placement cell assists students with job fairs and career counseling, though placement is limited for general courses.",
    "internship_opportunities": "The college encourages internships through external tie-ups and university programs.",
    "faculty": "The college has well-qualified faculty across departments, most of whom are NET/PhD qualified.",
    "exam_pattern": "Semester exams are conducted under HPU regulations, typically in November and May.",
    "attendance": "Minimum 75% attendance is required to sit in final exams.",
    "anti_ragging": "The college follows a strict anti-ragging policy and has a dedicated committee.",
    "ncc": "Yes, the college offers NCC for both boys and girls.",
    "nss": "Students can enroll in the National Service Scheme (NSS) to participate in community service.",
    "wifi": "Free Wi-Fi is available in the academic block for staff and students.",
    "canteen": "The college has a hygienic and affordable canteen offering snacks and meals.",
    "lab_facilities": "Science and computer labs are available and well-equipped for practical learning.",
    "computer_lab": "The computer lab has internet access and is available to all BCA and B.Sc students.",
    "student_union": "A student union is elected annually and represents student interests.",
    "cultural_events": "Events like annual day, youth festivals, and cultural fests are organized every year.",
    "fest_name": "The main cultural fest is known as 'Sanskriti Mahotsav'.",
    "academic_calendar": "The academic calendar follows Himachal Pradesh University guidelines.",
    "language_medium": "Most courses are taught in English and Hindi, depending on the department.",
    "alumni": "The college has an active alumni network that supports mentoring and guidance.",
    "classrooms": "Classrooms are spacious and equipped with basic teaching aids.",
    "transport": "The college is well-connected by road. Public buses and auto-rickshaws are easily available.",
    "location": "The college is located in the heart of Una town near Mini Secretariat.",
    "established": "Govt PG College Una was established in 1968.",
    "naac": "The college is NAAC accredited with a good rating.",
    "university_affiliation": "It is affiliated with Himachal Pradesh University, Shimla.",
    "distance_learning": "Some programs may be available through IGNOU or HPU ICDEOL for distance learners.",
    "revaluation": "Yes, revaluation and rechecking options are available after results are declared.",
    "library_hours": "The library remains open from 9:30 AM to 4:30 PM on working days.",
    "faculty_list": "You can find the full list of faculty members on the college website or notice board.",
    "notice_board": "All important updates are displayed on the main notice board and the website.",
    "online_classes": "Online classes are conducted via Google Meet or Zoom during emergencies or vacations.",
    "career_guidance": "Career counseling sessions are organized by the guidance and placement cell.",
    "girls_facility": "A common room for girls and a separate washroom block is available.",
    "grievance_cell": "A grievance redressal cell is in place for resolving student complaints.",
    "pta": "Parent-Teacher Association meetings are held regularly to discuss academic progress.",
    "departmental_activities": "Each department conducts seminars, quizzes, and group discussions regularly.",
    "bridge_courses": "Bridge courses are offered at the beginning of the academic year to help new students.",
    "remedial_classes": "Remedial classes are available for academically weaker students.",
    "timetable": "The timetable is displayed on the notice board and updated every semester.",
    "seminars": "Seminars and guest lectures are frequently organized by departments.",
    "moocs": "Students are encouraged to enroll in online courses (MOOCs) from SWAYAM and NPTEL.",
    "id_card": "All students must carry their college ID card at all times on campus.",
    "discipline": "Strict discipline is maintained. Mobile usage is restricted during lectures.",
    "result": "Results are declared on the HPU website usually within two months after exams.",
    "recruiters": "Govt exams are the primary career path; few companies visit for direct recruitment.",
    "department_heads": "Each department has a head who supervises academics and student issues.",
    "minor_subjects": "Students can opt for minor subjects based on NEP 2020 guidelines.",
    "skill_courses": "Skill-based add-on courses like spoken English, computer basics are offered.",
    "attendance_portal": "Attendance records are maintained by the class teacher and shared when required.",
    "scholarship_portal": "Apply at https://scholarships.gov.in or visit college office for state schemes.",
    "medical_facility": "Basic first aid is available; nearest hospital is Regional Hospital Una.",
    "ragging_helpline": "Students can contact the anti-ragging helpline or faculty in charge directly.",
    "disciplinary_action": "Strict action is taken against misconduct or violation of college rules.",
    "minority_cell": "The college has a minority cell to support minority students.",
    "sc_st_cell": "Special support and guidance are provided for SC/ST students.",
    "placement_fairs": "The college occasionally collaborates with nearby institutions for job fairs.",
    "soft_skills": "Training in resume writing, interview preparation, and communication is provided.",
    "language_lab": "A language lab is available for improving spoken English and grammar.",
    "college_magazine": "Students can contribute articles and poetry to the annual college magazine.",
    "website": "Official website: https://gpgcuna.ac.in",
    "helpline": "You can contact the college at +91-1975-223838 for general queries.",
    "email": "Email your queries to gpguna-hp@nic.in",
    "holiday_list": "The academic calendar includes a list of gazetted and special holidays.",
    "internal_assessment": "Internal marks are based on attendance, assignments, and class tests.",
    "marksheet": "Mark sheets are issued by HPU through the college office after result declaration.",
    "admission_form": "Admission forms are available online on the college portal during admission season.",
    "campus_area": "The college campus is spread over approximately 10 acres.",
    "students_strength": "The college has over 4000 students enrolled in various programs.",
    "iqac": "The Internal Quality Assurance Cell ensures academic and administrative quality.",
    "financial_aid": "Students can apply for financial assistance if they meet eligibility criteria.",
    "gender_cell": "A women cell is active for safety and awareness programs.",
    "youth_festival": "The college participates in the HPU Youth Festival annually.",
    "students_corner": "Students can find updates, forms, and circulars at the Students Corner on the website.",
    "canteen_menu": "The canteen offers tea, samosas, rice, rajma, and other snacks at nominal rates.",
    "rainwater_harvesting": "The college promotes rainwater harvesting as part of eco-initiatives.",
    "student_feedback": "Students can give anonymous feedback on faculty and facilities every semester.",
    "erp_login": "ERP login credentials are provided at the time of admission.",
    "transfer": "You can apply for college transfer with valid reasons and university approval.",
    "migration_certificate": "Migration certificates are issued on request after course completion.",
    "convocation": "Degree certificates are distributed during convocation or can be collected from office.",
    "helpdesk": "The helpdesk is active during admission time and exam season for support.",
    "notice_updates": "Check the notice board or website daily for latest updates.",
    "exam_center": "Exam center is usually the college itself, unless specified otherwise.",
    "backlog_exam": "Students can reappear in backlog papers in the next exam cycle.",
    "college_events": "College hosts debate competitions, quiz contests, and environmental awareness drives.",
    "dress_code": "There is no formal dress code, but students are expected to wear decent clothing.",
    "pg_admission": "For PG programs, admission is merit-based and managed by HPU rules.",
    "exam_fees": "Exam form and fees are submitted before the deadline via offline or online mode.",
    "identity_proof": "Bring college ID or Aadhaar card during exams and official events.",
    "admission_status": "You can check your admission status on the notice board or website login.",
    "lost_id": "Lost ID cards can be reissued by applying in the office with a small fine.",
    "when_are_exams": "Exams are usually held in November (odd semester) and May (even semester) as per the HPU academic calendar.",

  "how_to_get_admission": "You can apply through the college's online portal or visit the college admission cell for offline submission.",
  "what_is_the_cutoff": "The cutoff varies by course and category. Merit lists are displayed on the notice board and website.",
  "admission_open_date": "Admissions usually open in June after 12th board results are declared.",
  "re_admission": "Students who drop out can reapply for admission subject to HPU rules and seat availability.",
  "entrance_exam": "Entrance exams are not required for most UG programs. Some PG programs may have entrance criteria.",
  "when_are_exams_held": "Semester exams are usually held in November and May. Practical exams are conducted prior to theory papers.",
  "how to apply for admission": "You can apply online or visit the college admission cell.",
"where to get admission form": "Forms are available online and at the office.",
"when will admission start": "Admissions usually begin in June after board results.",
"when is last admission date": "Usually in July. Check official site.",
"is admission form available online": "Yes, on the official website.",
"what courses are available here": "UG and PG courses like BA, BCom, MSc, etc.",
"how many courses are offered": "Multiple UG and PG programs are available.",
"do you offer bca course": "Yes, BCA is available as UG course.",
"is bba course available": "No, BBA is not currently offered.",
"what subjects are in bsc": "Physics, Chemistry, Maths, Bio, and more.",
"are pg courses available here": "Yes, PG courses like MA, MSc, MCom.",
"what is ug course fee": "UG fees range from ₹3000–₹5000 yearly.",
"when are semester exams held": "Exams are held in November and May.",
"where to check exam timetable": "Timetable is available on notice board.",
"how to apply for revaluation": "Submit revaluation form after result declaration.",
"how to check my result": "Visit HPU website or ask office.",
"how are internal marks given": "Based on assignments, tests, and attendance.",
"what is passing marks criteria": "As per HPU guidelines. Usually 35%.",
"can I reappear in exam": "Yes, through backlog or improvement exams.",
"does college provide hostel facility": "No hostel. Students stay in PGs nearby.",
"is library open on saturday": "Yes, 9:30 AM to 4:30 PM.",
"is free wifi available": "Yes, for students in academic block.",
"do you have computer lab": "Yes, with internet for CS students.",
"what are canteen timings": "Open during college hours till 3 PM.",
"is there girls common room": "Yes, with separate facilities for girls.",
"do you have parking space": "Limited parking available inside campus.",
"how many classrooms are there": "Over 40 classrooms available.",
"do you have science labs": "Yes, for physics, chemistry, biology.",
"how many teachers in college": "About 60+ experienced faculty members.",
"who is head of department": "Check department notice board or website.",
"how to contact faculty member": "Via official email or during office hours.",
"what qualifications do teachers have": "Most faculty are NET/PhD qualified.",
"where to find faculty list": "On college website or notice board.",
"what cultural events are held": "Annual Day, Youth Festival, Sanskriti Mahotsav.",
"how to join ncc unit": "Register during admission or orientation.",
"how to join nss": "Visit NSS office or faculty in charge.",
"what sports are available": "Cricket, volleyball, kabaddi, badminton, athletics.",
"do you have annual fest": "Yes, called Sanskriti Mahotsav.",
"how to get migration certificate": "Apply after course completion with documents.",
"how to request duplicate id": "Visit office and pay reissue fee.",
"where to check notice updates": "Main board and official website daily.",
"how to apply for scholarship": "Via NSP portal or college office.",
"where to submit admission form": "In admission cell or online.",
"do you provide bonafide certificate": "Yes, apply at college office.",
"is there dress code": "No official code. Dress decently.",
"how to contact grievance cell": "Details available on notice board.",
"are remedial classes available": "Yes, for weak students every semester.",
"do you conduct seminars": "Yes, regularly by all departments.",
"is career counseling available": "Yes, through guidance and placement cell.",
"where to submit feedback form": "Submit anonymously through suggestion box.",
"who is principal of college": "Check principal section on college website.",
"where is college located": "In Una near Mini Secretariat.",
"when was college established": "In 1968 under HPU.",
"college is affiliated to which university": "Affiliated with HPU Shimla.",
"is college naac accredited": "Yes, with a good rating.",
"what_are_common_fest_activities": "Debates, quizzes, dance, music, cultural programs.",
"how to apply for scholarship": "Via NSP portal or college office.",
    "where to submit admission form": "In admission cell or online.",
    "do you provide bonafide certificate": "Yes, apply at college office.",
    "is there dress code": "No official code. Dress decently.",
    "how to contact grievance cell": "Details available on notice board.",
    "are remedial classes available": "Yes, for weak students every semester.",
    "do you conduct seminars": "Yes, regularly by all departments.",
    "is career counseling available": "Yes, through guidance and placement cell.",
    "where to submit feedback form": "Submit anonymously through suggestion box.",
    "who is principal of college": "Check principal section on college website.",
    "where is college located": "In Una near Mini Secretariat.",
    "when was college established": "In 1968 under HPU.",
    "college is affiliated to which university": "Affiliated with HPU Shimla.",
    "is college naac accredited": "Yes, with a good rating.",
    "what is the timing of classes": "From 9:00 AM to 3:00 PM, Monday to Saturday.",
    "what documents are required for admission": "10th and 12th mark sheets, migration, ID proof, photographs.",
    "how to apply for pg admission": "Through merit list as per HPU guidelines.",
    "is there any entrance exam for pg": "Sometimes, depending on course and HPU rules.",
    "what is the contact number of college": "You can contact +91-1975-223838.",
    "what is the email of college": "Send queries to gpguna-hp@nic.in.",
    "what is the official website": "Visit https://gpgcuna.ac.in.",
    "is there any holiday list": "Yes, included in the academic calendar.",
    "how to apply for financial aid": "Apply through college office with eligibility proof.",
    "what is the student strength": "More than 4000 students are enrolled.",
    "what is the campus area": "The campus covers about 10 acres.",
    "does college provide placement": "Yes, through placement cell but limited for general courses.",
    "is there any placement fair": "Yes, occasionally with nearby institutions.",
    "how to prepare for interviews": "Attend soft skills and resume workshops.",
    "what is the name of main fest": "Sanskriti Mahotsav.",
    "how to join youth festival": "Register via department cultural committee.",
    "is ncc available for girls": "Yes, NCC is available for both boys and girls.",
    "is nss available for boys": "Yes, NSS is open to all students.",
    "are online classes available": "Yes, during emergencies via Google Meet or Zoom.",
    "where to check results": "On HPU website after declaration.",
    "how to apply for rechecking": "Submit rechecking form at exam cell.",
    "what is the helpline number": "Call +91-1975-223838 for queries.",
    "is there grievance redressal cell": "Yes, for resolving student complaints.",
    "what is the attendance rule": "Minimum 75 percent attendance required.",
    "how is internal assessment calculated": "By attendance, assignments, and class tests.",
    "how to get duplicate marksheet": "Apply in office after paying small fee.",
    "is id card mandatory": "Yes, carry your ID card at all times.",
    "is there a dress code": "No strict dress code, but decent clothing expected.",
    "how to use erp login": "Credentials are given during admission.",
    "can I apply for transfer": "Yes, with valid reason and university approval.",
    "is convocation organized": "Yes, degrees are given at convocation.",
    "where is medical facility available": "At Regional Hospital Una nearby.",
    "is ragging allowed": "No, strict anti-ragging rules are followed.",
    "what action is taken against misconduct": "Strict disciplinary action as per rules.",
    "is there a minority cell": "Yes, for support of minority students.",
    "is there a sc st cell": "Yes, special support is available.",
    "is there a language lab": "Yes, for improving English and grammar.",
    "can I contribute to college magazine": "Yes, submit articles or poems annually.",
    "what soft skills training is provided": "Interview, resume writing, communication skills.",
    "is rainwater harvesting practiced": "Yes, as part of eco initiatives.",
    "how to give feedback about faculty": "Through anonymous student feedback forms.",
"what is the exam pattern": "Exams follow HPU semester system in May and November.",
    "where is the exam center": "Usually at the college itself unless mentioned otherwise.",
    "how to apply for backlog exam": "Fill backlog form before the deadline.",
    "what is the process for improvement exam": "Apply through exam cell with required fee.",
    "what is the college timing": "Classes run from 9:00 AM to 3:00 PM.",
    "when are internal exams conducted": "Mid-semester or as per department schedule.",
    "is attendance compulsory": "Yes, 75 percent attendance is mandatory.",
    "how many departments are there": "There are over 20 academic departments.",
    "who is the head of mathematics department": "Check the notice board for latest details.",
    "who is the head of english department": "Details available on the college website.",
    "who is the librarian": "Contact library section for librarian details.",
    "how many books are in the library": "Thousands of academic and reference books.",
    "does library provide e resources": "Yes, access to e-journals and e-books is available.",
    "what are library hours": "9:30 AM to 4:30 PM on working days.",
    "is library open on sunday": "No, closed on Sundays and holidays.",
    "what sports events are held": "Cricket, volleyball, kabaddi, athletics competitions.",
    "does college celebrate annual day": "Yes, with cultural and prize distribution programs.",
    "when is annual fest celebrated": "Usually in October or November.",
    "can outsiders attend fest": "Only with invitation or entry passes.",
    "how to join cultural society": "Register during orientation with cultural committee.",
    "is there a photography club": "Yes, active under cultural activities.",
    "is there a debate society": "Yes, students can join through cultural club.",
    "how to participate in quiz competitions": "Apply through department notices.",
    "are technical fests organized": "Yes, by computer science department.",
    "how to join music club": "Register through cultural in-charge.",
    "are there drama competitions": "Yes, as part of youth festival.",
    "how to apply for hostel outside": "Private PGs are available near campus.",
    "does college provide transport": "No, students use public buses and autos.",
    "is there bike parking facility": "Yes, limited parking for bikes.",
    "is there car parking facility": "Limited space for faculty and staff cars.",
    "how many labs are in college": "Multiple labs for science and computers.",
    "is computer lab open for all": "Yes, mainly for CS and BSc students.",
    "what software is available in lab": "Basic programming and office software.",
    "is internet free in lab": "Yes, for academic use.",
    "does college provide ERP login": "Yes, credentials given during admission.",
    "how to recover lost ERP password": "Contact IT cell or admin office.",
    "is student union elected every year": "Yes, annually.",
    "who can contest in student elections": "Students fulfilling eligibility criteria.",
    "what is the role of student union": "To represent student issues and interests.",
    "how to give suggestions to union": "Submit in suggestion box or meet union leaders.",
    "are grievance forms available online": "Yes, through the official website.",
    "is there women grievance cell": "Yes, for girls’ safety and support.",
    "is there anti ragging helpline": "Yes, details on notice board.",
    "is ragging strictly prohibited": "Yes, zero tolerance towards ragging.",
    "is there CCTV in campus": "Yes, in key areas for security.",
    "how to report ragging case": "Contact faculty in charge or helpline.",
    "what is the emergency helpline number": "Call +91-1975-223838.",
    "is there first aid facility": "Yes, basic first aid available.",
    "where is nearest hospital": "Regional Hospital Una.",
    "is there medical room in campus": "Yes, for first aid.",
    "does college have counseling center": "Yes, for mental health and career guidance.",
    "what is the role of IQAC": "To ensure academic and administrative quality.",
    "what are bridge courses": "Short courses at session start for weak students.",
    "what are remedial classes": "Extra classes for academically weaker students.",
    "what skill courses are available": "Spoken English, computer basics, soft skills.",
    "are MOOCs encouraged": "Yes, from SWAYAM and NPTEL.",
    "can students get certificates from MOOCs": "Yes, after completing the course.",
    "is there a language lab": "Yes, for English and grammar improvement.",
    "how to join language lab classes": "Register at language department.",
    "is there any youth festival": "Yes, HPU Youth Festival annually.",
    "how to participate in youth festival": "Through department selection.",
    "is there any eco club": "Yes, organizes environmental drives.",
    "what eco initiatives are taken": "Rainwater harvesting, plantation drives.",
    "is NSS compulsory": "No, voluntary.",
    "is NCC compulsory": "No, voluntary.",
    "how to apply for NCC certificate": "After completion of training period.",
    "what benefits of NCC": "Preference in defense and govt jobs.",
    "what benefits of NSS": "Certificates help in higher education admission.",
    "is PTA meeting held": "Yes, regularly.",
    "who can attend PTA meeting": "Parents and teachers of enrolled students.",
    "what is academic calendar": "Follows Himachal Pradesh University guidelines.",
    "where to get academic calendar": "From notice board or website.",
    "what is holiday list": "Part of academic calendar.",
    "how to check holiday list": "Available on college website.",
    "are national holidays observed": "Yes, as per govt notification.",
    "is Saturday working day": "Yes, till 3:00 PM.",
    "is Sunday a holiday": "Yes, college remains closed.",
    "how to get admission form offline": "From the admission cell in campus.",
    "how to pay admission fees": "Through online portal or college office.",
    "is fee payment online": "Yes, available on ERP.",
    "is fee refundable": "As per university refund rules.",
    "can fees be paid in installments": "Usually not, unless specified.",
    "how to apply for scholarship offline": "Submit form at college scholarship cell.",
    "which scholarships are available": "State and central govt schemes.",
    "who is eligible for scholarships": "SC, ST, OBC, EWS students.",
    "how to apply for EWS scholarship": "Via NSP portal with income certificate.",
    "what documents needed for scholarship": "Income, caste, domicile certificates.",
    "can general category apply for scholarship": "Yes, under EWS or merit schemes.",
    "where to check scholarship status": "On NSP portal or college notice board.",
    "how to collect scholarship money": "Directly credited to bank account.",
    "is Aadhaar mandatory for scholarship": "Yes, for DBT transfer.",
    "does college provide financial aid": "Yes, if criteria met.",
    "what is grievance redressal cell role": "To resolve student complaints.",
    "who is the grievance officer": "Details on notice board.",
    "can students email grievances": "Yes, to official email.",
    "is feedback form anonymous": "Yes, for genuine response.",
    "what is student feedback used for": "Improving faculty and facilities.",
    "is there students corner on website": "Yes, for forms and circulars.",
    "what is published in college magazine": "Articles, poems, and student work.",
    "how to submit article for magazine": "Submit to magazine committee.",
    "how often is magazine published": "Annually.","when does new session start": "Usually in July or August after admissions.",
    "how to collect id card": "From admin office after admission confirmation.",
    "what to do if id card lost": "Apply in office with small reissue fee.",
    "is identity card compulsory": "Yes, always carry in campus.",
    "how to update mobile number in records": "Submit request at office.",
    "how to update email id in records": "Contact ERP or admin office.",
    "how to get bonafide certificate": "Apply at admin office with form.",
    "how to get character certificate": "Issued by principal on request.",
    "how to get migration certificate": "Apply after course completion.",
    "how to apply for transfer certificate": "Submit application with documents.",
    "can I transfer to another college": "Yes, with university approval.",
    "how to apply for duplicate mark sheet": "Through HPU Shimla with fee.",
    "how to apply for convocation": "Fill form when dates are announced.",
    "when is convocation held": "As per university schedule.",
    "how to collect degree certificate": "From office after convocation.",
    "what is the grading system": "As per HPU guidelines (CGPA system).",
    "what is the minimum passing marks": "Usually 35 percent.",
    "how to apply for rechecking": "Fill revaluation form after result.",
    "what is last date for revaluation": "Within 15 days of result declaration.",
    "is there improvement exam option": "Yes, under HPU rules.",
    "how to apply for backlog exam": "Submit form at exam cell.",
    "where to check result": "On HPU website or college notice board.",
    "when will result be declared": "Within 2 months after exams.",
    "how to apply for answer sheet photocopy": "Submit request at exam section.",
    "does college provide exam center details": "Yes, displayed on notice board.",
    "can we use calculator in exams": "Only if allowed by university.",
    "what items allowed in exam hall": "ID card, admit card, stationery.",
    "are mobile phones allowed in exam hall": "No, strictly prohibited.",
    "how to apply for admit card": "Generated through ERP before exams.",
    "where to collect admit card": "From class teacher or exam section.",
    "what is the timing of theory exams": "Usually 9:00 AM or 2:00 PM shifts.",
    "when are practical exams conducted": "Before theory papers.",
    "who conducts practical exams": "External and internal examiners.",
    "how to prepare internal assessment": "Attend classes and submit assignments.",
    "what is weightage of internal marks": "As per HPU scheme.",
    "how many assignments per semester": "Varies by subject.",
    "who checks internal assignments": "Subject teachers.",
    "how are attendance marks calculated": "Based on class presence percentage.",
    "what happens if attendance below 75": "May be detained from exams.",
    "how to apply for attendance relaxation": "Through application to principal.",
    "does college organize blood donation camps": "Yes, under NSS activities.",
    "are tree plantation drives held": "Yes, under eco club.",
    "are cleanliness drives held": "Yes, regularly.",
    "are awareness rallies organized": "Yes, for social issues.",
    "does college celebrate yoga day": "Yes, on 21st June every year.",
    "is there Red Ribbon club": "Yes, for AIDS awareness.",
    "is there anti drug cell": "Yes, organizes awareness campaigns.",
    "are there gender equality programs": "Yes, by women cell.",
    "is there cyber security awareness": "Yes, workshops organized.",
    "does college celebrate teachers day": "Yes, on 5th September.",
    "does college celebrate independence day": "Yes, with cultural programs.",
    "does college celebrate republic day": "Yes, flag hoisting and events.",
    "does college celebrate himachal day": "Yes, with cultural activities.",
    "is fresher party organized": "Yes, by seniors for newcomers.",
    "is farewell party given": "Yes, for final year students.",
    "how to book seminar hall": "Through office permission.",
    "how many seminar halls available": "At least one main hall.",
    "does college have auditorium": "Yes, for big events.",
    "how to participate in elocution competition": "Register at cultural cell.",
    "how to participate in essay writing competition": "Check notices for registration.",
    "how to participate in poetry competition": "Register through cultural committee.",
    "are inter college competitions held": "Yes, regularly.",
    "does college send teams for inter university": "Yes, for sports and cultural.",
    "how to join alumni association": "Register online or through office.",
    "what activities alumni do": "Mentoring, donations, career guidance.",
    "is there alumni meet": "Yes, annually or biannually.",
    "how to contact alumni": "Through alumni cell.",
    "does college provide placements": "Limited placements via career cell.",
    "what recruiters visit college": "Mainly govt sector guidance.",
    "are job fairs organized": "Sometimes, with nearby institutions.",
    "does placement cell provide resume help": "Yes, resume building sessions.",
    "does placement cell provide interview training": "Yes, soft skills workshops.",
    "are internships compulsory": "Encouraged, not always compulsory.",
    "how to apply for internship": "Through placement cell or department.",
    "are stipend internships available": "Depends on organization.",
    "can students intern during vacations": "Yes, recommended.",
    "what are timings of canteen": "Till 3:00 PM on working days.",
    "what food available in canteen": "Tea, snacks, meals like rajma rice.",
    "is canteen affordable": "Yes, nominal rates.",
    "is drinking water available": "Yes, filtered water coolers installed.",
    "is water purifier available": "Yes, in main block.",
    "is there girls common room": "Yes, with seating and washroom.",
    "is there boys common room": "No, only girls common room.",
    "are there separate toilets for girls": "Yes, in girls block.",
    "is there sanitary pad vending machine": "Yes, in girls common room.",
    "is there 24 hour electricity": "Yes, with backup in labs.",
    "does college have rainwater harvesting": "Yes, as eco initiative.",
    "is there solar power facility": "Partially installed.",
    "how big is the campus": "Around 10 acres.",
    "how many students in college": "Over 4000 enrolled.",
    "is campus wifi enabled": "Yes, in academic block.",
    "how to connect to wifi": "Get credentials from IT cell.",
    "is wifi free for students": "Yes, for academic purpose.",
    "is wifi available in hostel": "No hostel, only PGs nearby.",
    "are there CCTV cameras in campus": "Yes, for security.",
    "is campus ragging free": "Yes, strict anti ragging policy.",
    "how to contact principal": "Through office or email.",
    "what is official email of college": "gpguna-hp@nic.in",
    "what is helpline number": "+91-1975-223838",
    "what is official website": "https://gpgcuna.ac.in","does college organize educational tours": "Yes, departments arrange field visits.",
    "are industrial visits conducted": "Yes, for commerce and science students.",
    "does college organize study tours": "Yes, based on department plans.",
    "how to join study tour": "Register with department coordinator.",
    "are students allowed on picnic": "Yes, with prior permission.",
    "is there medical facility in college": "Only first aid available.",
    "nearest hospital to college": "Regional Hospital Una.",
    "does college have ambulance": "No, but hospital is nearby.",
    "is there first aid kit in labs": "Yes, available in every lab.",
    "who to contact in case of medical emergency": "Inform faculty or admin office.",
    "does college celebrate world environment day": "Yes, every 5th June.",
    "does college observe international yoga day": "Yes, with mass yoga sessions.",
    "are there awareness lectures": "Yes, by invited experts.",
    "is there placement brochure": "Yes, provided by placement cell.",
    "how to apply for add on courses": "Forms available in departments.",
    "what add on courses are offered": "Spoken English, Computer Basics, etc.",
    "are bridge courses offered": "Yes, at start of session.",
    "are remedial classes free": "Yes, for weak students.",
    "who conducts remedial classes": "Subject faculty members.",
    "how to get timetable": "On notice board and ERP portal.",
    "when is timetable updated": "At beginning of each semester.",
    "can timetable change mid semester": "Yes, if needed.",
    "does college have digital notice board": "Yes, on main building.",
    "are circulars available online": "Yes, at Students Corner on website.",
    "where to check exam notifications": "Notice board and official website.",
    "where to get admit card printout": "From ERP portal or exam cell.",
    "is ERP login given to all students": "Yes, after admission.",
    "how to reset ERP password": "Contact IT cell.",
    "is ERP portal for parents too": "No, only for students and staff.",
    "does ERP show attendance": "Yes, attendance records available.",
    "does ERP show internal marks": "Yes, after submission by teachers.",
    "are library books barcoded": "Yes, for easy issue and return.",
    "how many books can I issue": "Usually 2–3 books at a time.",
    "for how many days books issued": "Generally 14 days.",
    "what if book lost": "Pay fine or replace book.",
    "is there fine for late return": "Yes, nominal per day fine.",
    "can reference books be issued": "No, only for reading in library.",
    "does library provide e books": "Yes, via e resources.",
    "how to get library card": "Apply at library counter.",
    "is library open in vacations": "Yes, on working days.",
    "how to access online journals": "Through library login credentials.",
    "are library computers available": "Yes, for academic use.",
    "does library have reading room": "Yes, with seating capacity.",
    "can we bring bags inside library": "No, only notebooks allowed.",
    "are mobile phones allowed in library": "Kept on silent mode only.",
    "does library conduct orientation": "Yes, for new students.",
    "who is librarian of college": "Check library notice board.",
    "is there career guidance cell": "Yes, under placement cell.",
    "does career cell organize workshops": "Yes, on resume and skills.",
    "are govt job coaching sessions held": "Yes, occasionally.",
    "does career cell arrange guest lectures": "Yes, from industry experts.",
    "does career cell guide for higher studies": "Yes, counseling available.",
    "how to register in career guidance cell": "Contact placement officer.",
    "are there entrepreneurship programs": "Yes, through career cell.",
    "does college have innovation cell": "Yes, supports startups.",
    "does college support startups": "Guidance provided via innovation cell.",
    "does college have incubation center": "Not yet, but tie ups possible.",
    "does college have research cell": "Yes, promotes student research.",
    "are students encouraged for research": "Yes, in PG programs.",
    "are there research projects for UG": "Yes, as per NEP guidelines.",
    "how to apply for research project": "Through department head.",
    "does college subscribe to magazines": "Yes, academic and competitive.",
    "are daily newspapers available in library": "Yes, Hindi and English dailies.",
    "are notice boards in each block": "Yes, department wise boards.",
    "is there lost and found section": "Yes, report to admin office.",
    "how to report lost items": "Inform office with details.",
    "is there student union in college": "Yes, elected annually.",
    "what is role of student union": "Represents student issues.",
    "how are union elections held": "As per HPU guidelines.",
    "when are student union elections": "Usually in September.",
    "who can contest union elections": "As per Lyngdoh Committee rules.",
    "are union elections fair": "Yes, monitored strictly.",
    "is there grievance redressal cell": "Yes, for student complaints.",
    "how to submit complaint": "In writing at grievance cell.",
    "can complaints be anonymous": "Yes, through suggestion box.",
    "how long grievance resolution takes": "Usually 7–10 working days.",
    "is there anti sexual harassment cell": "Yes, under women cell.",
    "how to contact women cell": "Details on notice board.",
    "does college celebrate women day": "Yes, on 8th March.",
    "are self defense workshops held": "Yes, for girl students.",
    "is there minority cell": "Yes, supports minority students.",
    "is there sc st cell": "Yes, for SC/ST support.",
    "does college have equal opportunity cell": "Yes, for all communities.",
    "are motivational lectures held": "Yes, by experts and alumni.",
    "are competitive exam seminars held": "Yes, UPSC and SSC guidance.",
    "is there skill development cell": "Yes, under placement section.",
    "are spoken english classes held": "Yes, as add on course.",
    "is there language lab": "Yes, for English improvement.",
    "are moocs promoted": "Yes, SWAYAM and NPTEL courses.",
    "is there ict facility in classrooms": "Yes, projectors in some rooms.",
    "are smart classes available": "Yes, limited smart classrooms.",
    "does college provide projector facility": "Yes, for seminars and classes.",
    "are online classes held": "Yes, during emergencies.",
    "which platform used for online classes": "Google Meet or Zoom.",
    "is there attendance in online classes": "Yes, through google forms.",
    "does college use erp for assignments": "Yes, in some departments.",
    "are recorded lectures available": "Sometimes, if faculty shares.",
    "is there whatsapp group for notices": "Yes, department wise groups.",
    "is telegram used for updates": "Sometimes, for exam info.",
    "are email updates sent to students": "Yes, during admissions and exams.",
    "can parents contact teachers directly": "Yes, during PTA meetings.",
    "how often PTA meetings held": "Once every semester.",
    "what is agenda of PTA meetings": "Academic progress and issues.",
    "are parents informed about attendance": "Yes, during meetings.",
    "is there ERP login for parents": "No, only for students.", "does college celebrate independence day": "Yes, with flag hoisting and cultural programs.",
    "does college celebrate republic day": "Yes, every 26th January.",
    "are national festivals celebrated": "Yes, with full participation.",
    "does college organize blood donation camps": "Yes, through NSS.",
    "does college organize cleanliness drives": "Yes, as part of Swachh Bharat.",
    "are tree plantation drives held": "Yes, by eco club and NSS.",
    "does college have eco club": "Yes, to promote environment awareness.",
    "are plastic free campaigns conducted": "Yes, regularly.",
    "is rainwater harvesting promoted": "Yes, as part of eco initiatives.",
    "does college use solar panels": "Yes, partially for electricity.",
    "is there waste segregation in campus": "Yes, dry and wet waste bins provided.",
    "are cultural competitions held": "Yes, dance, drama, singing, etc.",
    "is there annual prize distribution": "Yes, for academics and sports.",
    "are inter college competitions held": "Yes, as per HPU calendar.",
    "does college participate in youth festival": "Yes, organized by HPU.",
    "what is main cultural fest": "Sanskriti Mahotsav.",
    "does college host debate competitions": "Yes, every year.",
    "are quiz contests organized": "Yes, department wise and college level.",
    "does college conduct talent hunt": "Yes, at start of academic year.",
    "is there farewell party for final year": "Yes, organized by juniors.",
    "does college celebrate fresher party": "Yes, organized for new students.",
    "are photography competitions held": "Yes, during youth festival.",
    "are essay competitions held": "Yes, on important occasions.",
    "does college celebrate teachers day": "Yes, on 5th September.",
    "does college celebrate hindi diwas": "Yes, on 14th September.",
    "does college celebrate international womens day": "Yes, with awareness programs.",
    "are annual sports held": "Yes, every year.",
    "is there athletic meet": "Yes, part of sports activities.",
    "does college have inter class tournaments": "Yes, for cricket, volleyball, etc.",
    "are certificates given for sports": "Yes, to all participants and winners.",
    "does college give sports quota admission": "Yes, as per HPU rules.",
    "are NCC camps held": "Yes, in collaboration with army units.",
    "are NSS camps held": "Yes, 7 day and 1 day camps.",
    "does college give NSS certificate": "Yes, after successful participation.",
    "is NCC certificate useful for jobs": "Yes, for defense and govt jobs.",
    "does NSS help in career": "Yes, adds value in CV.",
    "does college provide guidance for NET exam": "Yes, through PG departments.",
    "does college provide coaching for UPSC": "Occasionally, through seminars.",
    "are alumni invited for lectures": "Yes, successful alumni share experience.",
    "is there alumni association": "Yes, active alumni network.",
    "how to join alumni association": "Register after graduation.",
    "does alumni provide scholarships": "Sometimes, for needy students.",
    "are alumni meets organized": "Yes, every year.",
    "does college publish annual magazine": "Yes, students contribute articles.",
    "can students submit poems in magazine": "Yes, creative writing is welcome.",
    "who edits college magazine": "Editorial board with faculty and students.",
    "are photographs included in magazine": "Yes, of events and achievements.",
    "does college have wall magazine": "Yes, updated by students.",
    "is there language club": "Yes, for spoken English and Hindi literature.",
    "is there science club": "Yes, organizes exhibitions.",
    "is there commerce club": "Yes, for management activities.",
    "is there cultural club": "Yes, for dance, drama, and music.",
    "does college host career fairs": "Yes, occasionally.",
    "does placement cell organize job fairs": "Yes, in collaboration with others.",
    "are internship fairs held": "Yes, through career guidance cell.",
    "does college collaborate with industries": "Yes, for projects and training.",
    "are moocs credits counted": "Yes, as per HPU guidelines.",
    "does college promote digital literacy": "Yes, through computer courses.",
    "are digital skills workshops held": "Yes, regularly.",
    "does college have ict training": "Yes, for teachers and students.",
    "is there spoken english lab": "Yes, in language lab.",
    "is there robotics club": "Not yet, may start soon.",
    "does college celebrate science day": "Yes, with exhibitions.",
    "does college celebrate mathematics day": "Yes, seminars are organized.",
    "does college observe constitution day": "Yes, with awareness programs.",
    "does college observe voters day": "Yes, with voter awareness drives.",
    "does college provide voter id help": "Yes, NSS helps students apply.",
    "is there counseling for stress management": "Yes, through guidance cell.",
    "are yoga classes conducted": "Yes, during yoga week.",
    "does college celebrate fit india week": "Yes, with fitness activities.",
    "is there anti tobacco campaign": "Yes, awareness rallies held.",
    "is there drug awareness campaign": "Yes, NSS conducts programs.",
    "does college provide mental health counseling": "Yes, through women and grievance cell.",
    "is there blood group checkup camp": "Yes, organized annually.",
    "does college organize health camps": "Yes, with local hospitals.",
    "is there vaccination camp in college": "Yes, during special drives.",
    "does college celebrate world health day": "Yes, with lectures.",
    "is there student helpdesk": "Yes, during admissions and exams.",
    "where to contact during admission": "Helpdesk near admission cell.",
    "where to contact during exams": "Exam cell helpdesk.",
    "does college have suggestion box": "Yes, for anonymous feedback.",
    "is feedback compulsory": "Yes, every semester.",
    "is feedback online or offline": "Both options available.",
    "how to give online feedback": "Through ERP portal.",
    "does feedback affect teachers": "Yes, reviewed by IQAC.",
    "who manages iqac": "Faculty and principal jointly.",
    "does iqac organize workshops": "Yes, for quality improvement.",
    "is there swachhata committee": "Yes, under NSS unit.",
    "does college promote energy saving": "Yes, awareness campaigns conducted.",
    "does college celebrate environment week": "Yes, every July.",
    "is there rainwater harvesting system": "Yes, in campus.",
    "does college have solar lights": "Yes, installed in campus.",
    "does college recycle waste": "Yes, partially.",
    "are green initiatives displayed": "Yes, on notice board.",
    "does college have garden": "Yes, maintained by eco club.",
    "is there gardener in college": "Yes, appointed staff.",
    "are gardening competitions held": "Yes, by eco club.",
    "does college have cafeteria": "Yes, hygienic canteen available.",
    "is canteen food affordable": "Yes, nominal rates.",
    "does canteen provide meals": "Yes, snacks and lunch.",
    "are canteen items subsidized": "Yes, for students.",
    "is outside food allowed": "Yes, but limited.",
    "does college have water coolers": "Yes, in every block.",
    "is filtered water available": "Yes, through RO system.",
    "are washrooms cleaned regularly": "Yes, by staff daily.",
    "are separate washrooms for girls": "Yes, in each block.",
    "is sanitary pad vending machine available": "Yes, in girls common room.",
    "is there facility for disabled students": "Yes, ramps available.",
    "does college provide wheelchairs": "Yes, on request.",
    "is there lift facility": "No, only ramps provided.",
    "does college have auditorium": "Yes, for cultural and academic events.",
    "is there seminar hall": "Yes, with projector.",
    "is there conference room": "Yes, for meetings.",
    "does college have exam hall": "Yes, large capacity hall.",
    "is there stage for cultural events": "Yes, in main hall.",
    "does college have sound system": "Yes, for events and seminars.",
    "does college provide mic system": "Yes, available on request.",
    "is photography allowed during events": "Yes, by permission.",
    "does college have youtube channel": "Yes, for official updates.",
    "does college post notices on social media": "Yes, on Facebook and Instagram.",
    "is there official whatsapp group": "Yes, for urgent notices.",
    "does college provide digital id card": "Yes, on ERP portal.",
    "how to reissue lost id card": "Apply at office with fee.",
    "is fine charged for lost id": "Yes, small fine applicable.",
    "does college issue provisional certificate": "Yes, from office.",
    "how to apply for bonafide certificate": "Submit application in office.",
    "does college issue character certificate": "Yes, after course completion.",
    "how to apply for migration certificate": "After completion, from office.",
    "how to get transfer certificate": "Apply through principal office.",
    "does college issue degree certificate": "Yes, during convocation.",
    "how to attend convocation": "Register when notice issued.",
    "can degree be collected later": "Yes, from office if missed.",
    "where to check holiday list": "On academic calendar and notice board.",
    "does college follow gazetted holidays": "Yes, as per govt rules.",
    "are special holidays announced": "Yes, by principal when required.",
    "does college organize farewell ceremony": "Yes, for final year students.",
    "does college organize orientation program": "Yes, for new students.",

}

# Extended Intent-Keyword Mapping
intent_keywords = {
    "greeting": [
        "hello", "hi", "hey", "namaste", "good morning", "good evening", "good afternoon",
        "yo", "sup", "howdy", "greetings", "salaam", "pranam", "ram ram", "hola", "bonjour",
        "hii", "helloo", "good day", "long time no see", "wassup", "jai hind"
    ],
    "help": [
        "help", "assist", "support", "guide", "need help", "can you help", "how to",
        "please help", "help me", "need assistance", "what to do", "suggest", "any idea",
        "tell me", "explain", "clear doubt", "i'm stuck", "need info", "can you guide",
        "solve", "fix", "instructions"
    ],
    "goodbye": [
        "bye", "goodbye", "see you", "take care", "ciao", "farewell",
        "catch you later", "see ya", "bye bye", "good night", "shabba khair",
        "phir milenge", "see you soon", "later", "talk to you later", "all the best",
        "so long", "peace out", "hasta la vista"
    ],
    "query": [
        "what", "how", "when", "why", "where", "which", "who", "whom",
        "whose", "can", "does", "do", "is", "are", "will", "shall", "could",
        "may", "might", "tell", "explain", "inform", "details about", "give info"
    ],
    "thanks": [
        "thanks", "thank you", "thx", "ty", "dhanyavad",
        "shukriya", "bahut dhanyavad", "grateful", "much obliged", "thanks a lot",
        "thank you so much", "thanx", "tnx", "great thanks", "bohot shukriya",
        "thank u", "appreciate it", "cheers", "big thanks", "million thanks"
    ],
    "admission": [
        "admission", "apply", "form", "enroll", "join", "register",
        "application form", "online admission", "offline admission", "seat", "enrollment",
        "prospectus", "fill form", "admission help", "new admission", "re admission",
        "counseling", "apply online", "submit form", "last date admission"
    ],
    "courses": [
        "courses", "subjects", "programs", "bca", "ba", "ma", "msc", "mcom", "bcom", "bba",
        "available courses", "ug courses", "pg courses", "stream", "options",
        "which courses", "degree", "diploma", "class", "majors", "specialization"
    ],
    "scholarship": [
        "scholarship", "fee waiver", "financial aid", "free", "govt scheme",
        "grant", "stipend", "help for fees", "student aid", "bursary",
        "merit scholarship", "need based aid", "fellowship", "funding", "loan waiver",
        "apply for scholarship", "minority scholarship", "ews aid", "sc st scholarship",
        "obc scholarship"
    ],
    "exam": [
        "exam", "test", "paper", "schedule", "timetable", "backlog",
        "midterm", "semester exam", "final exam", "marksheet", "exam date",
        "internal test", "lab exam", "online exam", "practical exam", "question paper",
        "exam center", "back exam", "improvement exam", "supplementary exam"
    ],
    "result": [
        "result", "marks", "score", "grade", "pass", "fail",
        "exam result", "publish result", "marksheet", "percentage", "rank",
        "cgpa", "sgpa", "score card", "when result declared", "result date",
        "how to check result", "mark list", "outcome", "pass list"
    ],
    "faculty": [
        "teacher", "faculty", "professor", "lecturer", "staff",
        "hod", "principal", "incharge", "mentor", "guide",
        "department head", "assistant professor", "associate professor", "sir", "madam",
        "faculty list", "teaching staff", "staff member", "class teacher", "instructor"
    ],
    "attendance": [
        "attendance", "present", "absent", "percent", "record",
        "minimum attendance", "required attendance", "class presence", "attendance sheet",
        "attendance rule", "low attendance", "attendance portal", "attendance issue",
        "shortage", "proxy", "attendance fine", "attendance update", "attendance criteria",
        "attendance percentage", "bunking"
    ],
    "hostel": [
        "hostel", "stay", "accommodation", "room",
        "mess", "pg", "living", "lodging", "boarding",
        "student stay", "dormitory", "residence", "night stay", "girls hostel",
        "boys hostel", "separate hostel", "private pg", "rent room", "college stay"
    ],
    "library": [
        "library", "books", "journal", "reading", "issue", "return",
        "library card", "study hall", "book bank", "magazines", "research papers",
        "reference books", "e library", "library hours", "library rules", "borrow",
        "renew book", "fine on book", "library id", "book issue", "book return"
    ],
    "ncc_nss": [
        "ncc", "nss", "service", "cadet", "volunteer",
        "enroll in ncc", "ncc unit", "join nss", "social service", "camps",
        "ncc certificate", "nss certificate", "army wing", "air wing", "navy wing",
        "community service", "blood donation", "awareness drive", "ncc camp", "nss camp"
    ],
    "events": [
        "event", "fest", "competition", "function", "cultural", "annual day",
        "farewell", "freshers party", "youth festival", "debate", "quiz",
        "dance", "music", "drama", "sanskriti mahotsav", "celebration",
        "teachers day", "sports day", "independence day", "republic day", "convocation"
    ],
    "placement": [
        "placement", "job", "campus", "interview", "recruitment", "career",
        "career guidance", "job fair", "campus drive", "companies", "recruiters",
        "internship", "career counseling", "package", "salary", "resume help",
        "mock interview", "career support", "jobs available", "career cell"
    ],
    "sports": [
        "sports", "games", "tournament", "match", "cricket", "volleyball",
        "football", "badminton", "kho kho", "kabaddi", "athletics",
        "basketball", "table tennis", "chess", "carrom", "sports quota",
        "annual sports", "track event", "sports ground", "inter college match"
    ],
    "canteen": [
        "canteen", "food", "snack", "lunch", "tea",
        "mess", "refreshment", "drinks", "juice", "meal",
        "affordable food", "canteen menu", "canteen timing", "canteen rate",
        "college food", "breakfast", "snack time", "canteen tea", "canteen samosa", "canteen lunch"
    ],
    "wifi": [
        "wifi", "internet", "network", "connection",
        "free wifi", "wifi password", "wifi issue", "college internet",
        "lab wifi", "wifi block", "wifi access", "wifi login", "wifi available",
        "wifi not working", "connect wifi", "wifi problem", "wifi details", "free internet"
    ],
    "discipline": [
        "discipline", "rules", "ragging", "ban", "code",
        "punishment", "anti ragging", "code of conduct", "strict rules",
        "complaint", "report issue", "fine", "expel", "warning",
        "grievance", "disciplinary action", "misconduct", "rules violation", "zero tolerance"
    ],
    "location": [
        "location", "where is", "address", "map", "reach",
        "college location", "how to reach", "college in una", "una college address",
        "near mini secretariat", "transport", "bus route", "college landmark", "directions",
        "gps location", "college address", "nearby area", "public transport", "distance"
    ],
    "timing": [
        "timing", "schedule", "class time", "open", "close",
        "college timing", "library hours", "office hours", "holiday timing", "exam timing",
        "class hours", "college open time", "college close time", "when open", "when close",
        "daily timing", "shift", "working days", "holiday list", "lecture timing"
    ],
    "fees": [
        "fees", "fee", "charge", "payment", "cost",
        "fee structure", "semester fee", "exam fee", "scholarship fee", "annual fee",
        "hostel fee", "library fee", "lab fee", "admission fee", "re exam fee",
        "pay fee", "submit fee", "fee details", "fee amount", "fee deposit"
    ],
    "id_card": [
        "id card", "identity", "college id",
        "college identity card", "student id", "lost id", "duplicate id",
        "id reissue", "id fine", "id application", "carry id", "identity proof",
        "id required", "photo id", "college badge", "college card", "college proof"
    ],
    "revaluation": [
        "revaluation", "recheck", "review marks",
        "exam recheck", "reval form", "reval fee", "marks revaluation",
        "paper recheck", "apply revaluation", "rechecking process",
        "result revaluation", "marks review", "reevaluation deadline", "submit revaluation"
    ],
    "migration": [
        "migration", "transfer", "shift college",
        "migration certificate", "college transfer", "tc", "apply migration",
        "transfer process", "migration fee", "change college", "migration approval",
        "shift course", "college shift", "apply transfer", "migration form"
    ],
    "convocation": [
        "convocation", "degree", "certificate",
        "degree ceremony", "degree distribution", "apply degree",
        "collect certificate", "provisional certificate", "convocation date",
        "convocation dress", "degree convocation", "convocation registration"
    ],
    "website": [
        "website", "portal", "online", "link",
        "college website", "official site", "college portal", "student login",
        "result website", "admission portal", "hpu portal", "online form", "apply online",
        "college link", "erp login", "college web", "portal link"
    ],
    "ok": [
        "ok", "okay", "okk", "okey", "acha", "hmm", "haan", "thik hai", "sahi", "fine",
        "great", "done", "cool", "alright", "sure", "perfect", "great work", "sounds good",
        "theek hai", "badiya", "chalo theek"
    ]
}
intent_keywords.update({
    "greeting": intent_keywords["greeting"] + [
        "good noon", "good day", "nice to see you", "how are you", "kem cho", "sasriakal", 
        "salaam alaikum", "adiab", "hello there", "long time", "jai shree ram", 
        "radhe radhe", "hare krishna", "good vibes"
    ],
    "help": intent_keywords["help"] + [
        "guide me", "help needed", "show me", "clarify", "any help", "need solution", 
        "tell how", "how do i", "what is the process", "can you explain", 
        "show details", "any guidance", "walk me through", "assist me", 
        "resolve my issue", "instruction please", "i want to know"
    ],
    "goodbye": intent_keywords["goodbye"] + [
        "bye for now", "talk later", "good night everyone", "see you again", "peace", 
        "have a good day", "goodbye friends", "phir milte hain", "see you tomorrow", 
        "bye dosto", "bye guys", "see you later", "khuda hafiz", "jaldi milenge"
    ],
    "query": intent_keywords["query"] + [
        "explain me", "tell details", "i want to know", "give me info", "share details", 
        "clarify this", "can you tell", "what about", "how about", "need explanation",
        "inform me", "i want details", "give knowledge", "query about", "my question is"
    ],
    "thanks": intent_keywords["thanks"] + [
        "thank you very much", "i appreciate it", "you helped me", "bohot shukriya dost", 
        "thanks buddy", "thanks friend", "bahut bada dhanyavad", "thanks bhai", "cheers buddy", 
        "shukriya ji", "appreciate a lot", "really grateful", "you saved me", "bohot madad hui"
    ],
    "admission": intent_keywords["admission"] + [
        "how to get admission", "fill admission form", "registration", "seat allotment", 
        "counselling", "direct admission", "online form", "offline form", 
        "documents for admission", "how to apply", "start admission", "end admission", 
        "admission rules", "merit list", "cutoff", "quota admission", "reservation admission"
    ],
    "courses": intent_keywords["courses"] + [
        "available programs", "list of subjects", "majors available", "what to study", 
        "options for ug", "options for pg", "course details", "bsc subjects", 
        "specialization subjects", "syllabus", "degree options", "career programs",
        "professional courses", "part time courses", "add on courses"
    ],
    "scholarship": intent_keywords["scholarship"] + [
        "fee discount", "apply nsp", "scholarship form", "apply for aid", "submit scholarship", 
        "scholarship eligibility", "government aid", "minority aid", "scholarship apply online", 
        "free education", "scholarship update", "student grant", "apply bursary", "merit aid", 
        "scholarship renewal"
    ],
    "exam": intent_keywords["exam"] + [
        "when is exam", "exam routine", "exam notification", "exam date sheet", 
        "exam registration", "exam fee", "exam center", "when are practicals", 
        "marks distribution", "internal assessment", "exam eligibility", "improvement test", 
        "exam slip", "download admit card", "exam rules", "exam instructions"
    ],
    "result": intent_keywords["result"] + [
        "when will result come", "declare result", "publish marks", "check cgpa", "see sgpa", 
        "when out result", "download marksheet", "print result", "result portal", 
        "score update", "marks obtained", "result out", "how many marks", "check percentage"
    ],
    "faculty": intent_keywords["faculty"] + [
        "teacher info", "meet faculty", "who is my teacher", "faculty contact", 
        "subject teacher", "professor info", "lecturer info", "guide info", "mentor details", 
        "faculty qualification", "faculty incharge", "class incharge", "faculty office hours"
    ],
    "attendance": intent_keywords["attendance"] + [
        "attendance shortage", "attendance problem", "minimum percent", "attendance update", 
        "how many percent required", "attendance check", "see my attendance", 
        "attendance percentage", "class bunk", "attendance record update", "attendance fine", 
        "attendance slip", "low attendance issue"
    ],
    "hostel": intent_keywords["hostel"] + [
        "girls hostel", "boys hostel", "apply hostel", "pg near college", "renting", 
        "accommodation nearby", "mess food", "student rooms", "private hostel", "dorm", 
        "paying guest", "room for rent", "stay facility", "nearby flats", "lodging info"
    ],
    "library": intent_keywords["library"] + [
        "borrow book", "return book", "renew book", "library hours", "library holidays", 
        "e resources", "digital library", "online books", "library membership", 
        "library card issue", "library fine", "library portal", "journals", "magazines available"
    ],
    "events": intent_keywords["events"] + [
        "cultural program", "annual function", "students fest", "debate competition", 
        "quiz contest", "youth fest", "farewell party", "freshers day", "college celebration", 
        "independence day", "republic day", "annual fest", "teachers day", "sports event", 
        "environment day"
    ],
    "sports": intent_keywords["sports"] + [
        "sports quota", "join cricket", "volleyball team", "football team", "athletics event", 
        "sports fest", "annual sports", "kabaddi match", "tournaments", "inter college sports", 
        "sports ground", "indoor games", "outdoor games", "sports competition", "team selection"
    ],
    "canteen": intent_keywords["canteen"] + [
        "canteen food", "canteen hours", "canteen menu", "tea stall", "snacks corner", 
        "lunch in canteen", "college mess", "canteen hygiene", "cheap food", "canteen timings", 
        "canteen samosa", "canteen tea", "canteen rice", "canteen rajma", "food facility"
    ],
    "wifi": intent_keywords["wifi"] + [
        "wifi login", "wifi id", "wifi password", "wifi reset", "internet connection", 
        "slow wifi", "wifi not working", "college wifi", "wifi portal", "wifi help", 
        "wifi speed", "wifi blocked", "wifi available", "connect wifi", "wifi signal"
    ],
    "fees": intent_keywords["fees"] + [
        "fee amount", "total fees", "annual fees", "semester fees", "fee due", 
        "fee last date", "submit fees", "fees deadline", "fees details", "exam fees", 
        "hostel fees", "lab fees", "online payment", "bank draft", "fees refund"
    ],
})
intent_keywords.update({
    "greeting": intent_keywords["greeting"] + [
        "hi bro", "hi sir", "hello mam", "namaskar", "good night", 
        "morning", "evening", "afternoon", "hey there", "yo"
    ],
    "help": intent_keywords["help"] + [
        "please help", "kya aap madad karenge", "help me out", "need info", 
        "kya process hai", "bataye", "can you guide", "show steps", 
        "mujhe samjhao", "kya karna hoga"
    ],
    "goodbye": intent_keywords["goodbye"] + [
        "ok bye", "bye bye", "chal phir milte", "milte hain", "fir milenge", 
        "take care bro", "chalo good night", "see ya", "alvida", "bye dost"
    ],
    "thanks": intent_keywords["thanks"] + [
        "bahut dhanyavad", "bohot shukriya", "thanks bhai", "thank you sir", 
        "thank you mam", "thanks a lot", "shukriya dost", "thank you very much", 
        "appreciate it", "bahut madad hui"
    ],
    "admission": intent_keywords["admission"] + [
        "admission kab hai", "form kab milega", "admission start date", 
        "admission end date", "admission fees", "admission portal", 
        "apply form", "admission last date", "admission kaise hoga", "admission status"
    ],
    "courses": intent_keywords["courses"] + [
        "kya kya course hai", "bsc hai kya", "bca available hai kya", "ug course", 
        "pg course", "bcom details", "ba subjects", "msc available", "ma courses", "mcom details"
    ],
    "exam": intent_keywords["exam"] + [
        "exam kab hai", "exam date", "exam time", "exam form", "exam fees", 
        "paper kab hai", "exam schedule", "exam ka time", "exam slip", "admit card"
    ],
    "result": intent_keywords["result"] + [
        "result kab aayega", "result check karo", "result ka link", "result date", 
        "result nikla kya", "marks dekho", "cgpa kitna hai", "percentage kitna hai", 
        "result kaise dekhe", "marksheet download"
    ],
    "fees": intent_keywords["fees"] + [
        "fees kitni hai", "fees detail", "fees kaise deni", "fees ka last date", 
        "fees jama karo", "fees online", "fees offline", "exam fees kitni", 
        "pg fees", "ug fees"
    ],
    "library": intent_keywords["library"] + [
        "library kab khulti hai", "library ka time", "books issue", "book return", 
        "library open hai kya", "library sunday ko", "library card", "library rules", 
        "library books list", "magazine available"
    ],
    "wifi": intent_keywords["wifi"] + [
        "wifi password", "wifi connect", "wifi kaise chalega", "wifi id", "wifi login", 
        "wifi slow hai", "wifi fast hai kya", "wifi ka link", "wifi access", "wifi ka problem"
    ],
    "canteen": intent_keywords["canteen"] + [
        "canteen kab khulta hai", "canteen food", "canteen menu", "canteen timing", 
        "canteen close hai kya", "canteen khana", "canteen tea", "canteen snacks", 
        "canteen hygiene", "canteen cheap hai kya"
    ],
    "sports": intent_keywords["sports"] + [
        "cricket team", "volleyball team", "kabaddi team", "football match", "athletics", 
        "sports ground", "sports event", "indoor games", "outdoor games", "annual sports"
    ],
    "placement": intent_keywords["placement"] + [
        "placement kab hoti hai", "job fair", "campus placement", "recruitment drive", 
        "career help", "interview prep", "resume help", "career counseling", "job ka chance", 
        "placement cell"
    ],
    "events": intent_keywords["events"] + [
        "annual fest", "college fest", "cultural program", "youth festival", "annual day", 
        "farewell", "freshers", "debate", "quiz", "teachers day"
    ],
    "discipline": intent_keywords["discipline"] + [
        "ragging rule", "discipline policy", "mobile allowed hai kya", "rules and regulation", 
        "bunk allowed", "ragging complaint", "strict rules", "code of conduct", 
        "discipline incharge", "anti ragging"
    ],
    "location": intent_keywords["location"] + [
        "college address", "college kahan hai", "college location", "college ka map", 
        "college kaha pada hai", "college reach", "near bus stand", "college ka address", 
        "college route", "how to reach college"
    ],
    "ok": intent_keywords["ok"] + [
        "acha", "haan", "theek hai", "hmm", "bilkul", "thik hai", "great", "done", 
        "fine", "sure", "okay bro", "ok sir", "ok mam", "yes", "haan ji"
    ]
})

# Extended Intent-Specific Responses
intent_responses.update({
    "greeting": "👋 Hello! Welcome to Govt PG College Una Chatbot. How may I help you?",
    "help": "🤝 Sure! Please tell me your query. I'm here to guide you.",
    "goodbye": "👋 Goodbye! Best of luck with your studies.",
    "thanks": "🙏 You’re most welcome! Glad to assist you.",
    "admission": "📝 Admissions usually open in June after board results. Forms are available online and in the office.",
    "courses": "🎓 We offer BA, BCom, BSc, BCA, MA, MCom, MSc, and add-on skill courses.",
    "scholarship": "💸 Apply for scholarships via the NSP portal or through the college office.",
    "exam": "🗓️ Semester exams are held in May and November. Practical exams are conducted before theory.",
    "result": "📢 Results are declared on the HPU website and notice board within two months of exams.",
    "faculty": "👩‍🏫 Most of our teachers are NET/PhD qualified and highly experienced.",
    "attendance": "📊 A minimum of 75% attendance is required to sit in exams.",
    "hostel": "🏠 Sorry, hostel facility is not available. Students usually stay in PGs nearby.",
    "library": "📚 Our library has thousands of books and remains open 9:30 AM to 4:30 PM.",
    "ncc_nss": "🚩 You can join NCC or NSS at the time of admission or through the respective coordinators.",
    "events": "🎉 Events like Annual Day, Youth Festivals, and Sanskriti Mahotsav are celebrated every year.",
    "placement": "💼 Placement cell organizes job fairs and provides career guidance.",
    "sports": "🏏 Facilities for cricket, volleyball, badminton, kabaddi, and athletics are available.",
    "canteen": "🍽️ The canteen serves tea, snacks, and meals at affordable rates.",
    "wifi": "📶 Free Wi-Fi is available in the academic block for students and staff.",
    "discipline": "🚫 Ragging is strictly prohibited. Students are expected to follow college rules.",
    "location": "📍 The college is located in Una, near Mini Secretariat, Himachal Pradesh.",
    "timing": "🕘 Classes run from 9:00 AM to 3:00 PM, Monday to Saturday.",
    "fees": "💰 UG fees are ₹3000–₹5000 yearly; PG fees are slightly higher.",
    "id_card": "🆔 All students must carry their college ID card while on campus.",
    "revaluation": "🔁 Revaluation forms are available after results are declared.",
    "migration": "📄 Migration certificates are issued after course completion on request.",
    "convocation": "🎓 Convocation is held annually. Degree certificates are distributed then.",
    "website": "🌐 Visit https://gpgcuna.ac.in for latest updates.",
    "ok": "👍 Okay! Let me know if you need more help.",
    "admission_process": "📌 You can apply online or offline through the admission cell.",
    "admission_last_date": "📅 Last date for admission is usually in July. Check official notices for updates.",
    "documents_required": "🗂️ Bring your 10th, 12th mark sheets, photos, ID proof, and character certificate.",
    "cutoff": "📈 Cutoff lists are displayed on the notice board and college website.",
    "internship_opportunities": "👩‍💻 Internships are encouraged through university and external tie-ups.",
    "anti_ragging": "🚫 A strict anti-ragging committee ensures student safety.",
    "girls_facility": "👩‍🎓 A common room and separate washroom block are available for girls.",
    "pta": "👨‍👩‍👧 Parent-Teacher Association meetings are organized regularly.",
    "remedial_classes": "📘 Remedial classes are arranged for academically weaker students.",
    "bridge_courses": "📝 Bridge courses are held to help new students adjust to college curriculum.",
    "erp_login": "🔑 ERP login credentials are given during admission.",
    "notice_updates": "📌 Check the notice board or website daily for latest information.",
    "helpdesk": "☎️ Helpdesk is available during admission and exam season.",
    "medical_facility": "🏥 Basic first aid is available. Nearest hospital: Regional Hospital Una.",
    "ragging_helpline": "📞 Contact the anti-ragging helpline or committee in charge immediately.",
    "iqac": "📊 IQAC ensures quality improvement in academics and administration.",
    "holiday_list": "📅 Holiday list is provided in the academic calendar.",
    "marksheet": "📄 Mark sheets are issued by HPU through the college office.",
    "career_guidance": "💼 Career counseling sessions are conducted regularly.",
    "grievance_cell": "📩 Submit your complaints to the grievance redressal cell.",
    "students_strength": "👩‍🎓 The college has more than 4000 enrolled students.",
    "campus_area": "🏫 The campus covers about 10 acres of land.",
    "college_events": "🎤 We host debates, quizzes, and awareness drives.",
    "lost_id": "🆔 Apply in the office with a small fine for a duplicate ID card.",
    "canteen_menu": "🍛 The canteen serves tea, rice, rajma, samosas, and snacks.",
    "student_union": "🗳️ A student union is elected every year.",
    "fest_name": "🎭 The main cultural fest is called Sanskriti Mahotsav.",
    "classrooms": "🏫 The college has spacious classrooms equipped with teaching aids.",
    "department_heads": "👨‍🏫 Each department has a Head for student issues and academics.",
    "minor_subjects": "📚 Students can choose minor subjects as per NEP 2020.",
    "skill_courses": "💡 Add-on courses like spoken English and computer basics are offered.",
    "language_lab": "🗣️ A language lab is available for English communication skills.",
    "financial_aid": "💸 Eligible students may apply for financial aid.",
    "student_feedback": "📝 Students can provide anonymous feedback every semester.",
    "youth_festival": "🎶 The college participates in HPU Youth Festivals annually.",
    "exam_center": "🏫 Usually exams are held in the college itself unless otherwise mentioned.",
    "backlog_exam": "🔄 Yes, backlog exams are conducted in the next semester cycle.",
    "internal_assessment": "📊 Internal marks are given for class tests, assignments, and attendance.",
    "recruiters": "🏢 Most students prepare for govt exams. A few companies may visit for recruitment.",
    "online_classes": "💻 Online classes are conducted via Zoom or Google Meet when required.",
    "academic_calendar": "📅 Academic calendar follows Himachal Pradesh University guidelines.",
    "departmental_activities": "📘 Departments conduct seminars, workshops, and quiz competitions.",
    "soft_skills": "🗣️ Soft skills training includes resume writing and interview preparation.",
    "college_magazine": "📰 Students can write articles and poetry for the annual magazine.",
    "gender_cell": "👩 Women cell is active for awareness and safety programs.",
    "minority_cell": "🕌 A minority cell provides special support to minority students.",
    "sc_st_cell": "✊ Special support and guidance are available for SC/ST students.",
    "placement_fairs": "💼 The college collaborates with nearby institutions for job fairs.",
    "rainwater_harvesting": "💧 The college has eco-friendly initiatives like rainwater harvesting.",
    "disciplinary_action": "⚖️ Strict action is taken against misconduct or rule violations.",
    "erp_support": "💻 For ERP login issues, contact the IT cell of the college.",
    "holiday_notice": "📌 Holiday notices are displayed on the main board and website.",
    "how_to_contact_office": "☎️ You can call the office at +91-1975-223838 or visit during working hours.",
    "lost_documents": "📄 Report lost documents to the office immediately with an application.",
    "id_card_rules": "🆔 ID cards must be shown on demand by security or faculty.",
    "how_to_get_bonafide": "📑 Apply in the office for a bonafide certificate with an application.",
    "exam_fees": "💰 Exam fees are submitted online or at the office before the deadline.",
    "transfer": "🔁 College transfer is possible with valid reasons and HPU approval.",
    "convocation_certificate": "🎓 Collect your degree certificate during convocation or from the office.",
    "canteen_rules": "🍴 Maintain cleanliness and avoid food wastage in the canteen.",
    "discipline_policy": "📘 Mobile phones are not allowed during lectures.",
    "hostel_alternative": "🏠 Students usually stay in PGs or rented rooms nearby.",
    "college_map": "🗺️ A campus map is available at the helpdesk and website.",
    "lost_and_found": "🔍 Lost and found items can be reported at the main office.",
    "photocopy_facility": "📠 Photocopy facility is available inside the campus.",
    "computer_lab_rules": "💻 Labs can be used during scheduled hours only.",
    "notice_board_location": "📌 The main notice board is located near the administrative block.",
    "emergency_contact": "☎️ In emergencies, contact the principal office immediately.",
    "feedback_system": "📝 Feedback forms are available online and in the office.",
    "remedial_registration": "📚 Register for remedial classes through your department.",
    "seminars_guest": "🎤 Guest lectures are regularly conducted by subject experts.",
    "student_projects": "📑 Final year students can present projects through their departments.",
    "classroom_rules": "📘 Maintain discipline and avoid disturbing lectures.",
    "sports_registration": "🏅 Register with the sports department to participate in games.",
    "placement_guidance": "💼 Career and placement guidance is given in the placement cell.",
    "skill_course_registration": "🖊️ Add-on skill course registration is open at the beginning of session.",
    "ncc_camps": "🚩 NCC cadets can attend state and national level camps.",
    "nss_activities": "🤝 NSS volunteers engage in community service and awareness drives.",
    "transport_facility": "🚌 Public buses and autos are easily available outside the college.",
    "canteen_specials": "🍛 The canteen serves rajma-chawal and samosas as special items.",
    "library_membership": "📚 All students automatically become library members after admission.",
    "how_to_issue_books": "📖 Show your ID card to issue books from the library counter.",
    "returning_books": "📕 Books must be returned within the due date to avoid fines.",
    "fine_policy": "💰 A small fine is charged for late return of library books.",
    "reading_room": "📖 The library has a reading room for silent study.",
    "digital_library": "💻 E-resources and e-books are available through the library portal.",
    "alumni_meet": "🤝 Alumni meet is organized to connect past and present students.",
    "youth_festival_events": "🎶 Youth Festivals include music, dance, and debate competitions.",
    "cultural_committee": "🎭 The cultural committee organizes annual programs.",
    "discipline_committee": "⚖️ A discipline committee monitors campus discipline.",
    "faculty_office_hours": "👩‍🏫 Meet faculty during their office hours for academic help.",
    "attendance_check": "📊 Attendance records can be checked through your class teacher.",
    "erp_password_reset": "🔑 Contact IT cell for ERP password reset.",
    "notice_updates_online": "🌐 Notices are updated daily on the official website.",
    "health_camps": "🏥 Free health camps are organized for students occasionally.",
    "blood_donation": "🩸 NSS organizes blood donation camps every year.",
    "environment_club": "🌳 The Eco Club organizes tree plantation and awareness drives.",
    "student_awards": "🏆 Best performing students are awarded on Annual Day.",
    "principal_meeting": "👨‍💼 You can meet the principal during designated office hours.",
    "canteen_menu": "🍜 Today's canteen menu is displayed at the counter every morning.",
    "canteen_feedback": "📝 You can give canteen feedback at the office suggestion box.",
    "sports_facility_timings": "🏟️ Sports ground is open from 7 AM to 6 PM daily.",
    "lab_facilities": "🔬 Labs for Physics, Chemistry, Biology, and Computer Science are available.",
    "computer_lab_timings": "💻 The computer lab is open from 10 AM to 4 PM.",
    "college_magazine_submission": "📰 Submit your articles to the editorial committee by the given deadline.",
    "student_union": "🗳️ A student union is elected annually to represent student interests.",
    "ragging_policy": "🚫 Ragging is banned as per Supreme Court guidelines. Report immediately if witnessed.",
    "student_corner": "📌 Students Corner section on the website provides forms and notices.",
    "financial_aid": "💸 Apply for financial aid in the office with supporting documents.",
    "bridge_courses": "📖 Bridge courses help new students adapt to college-level studies.",
    "iqac": "📊 Internal Quality Assurance Cell maintains academic quality standards.",
    "pta_meetings": "👪 PTA meetings are organized regularly for academic discussions.",
    "medical_facility": "🏥 First-aid facility is available; hospital is nearby.",
    "grievance_redressal": "📩 Drop your complaints in the grievance box or contact the grievance cell.",
    "youth_festival": "🎶 College participates in HPU Youth Festival every year.",
    "rainwater_initiative": "💧 Rainwater harvesting is part of the eco-friendly initiatives.",
    "environment_awareness": "🌱 Environmental awareness programs are held regularly.",
    "discipline_rules": "⚖️ Mobile phones are not allowed during class hours.",
    "holiday_list": "📅 The holiday list is included in the academic calendar.",
    "transfer_certificate": "📜 Apply in the office for a transfer certificate.",
    "migration_process": "📄 Migration certificates are issued after course completion.",
    "lost_id_process": "🆔 Apply for duplicate ID in the office with a fine.",
    "feedback_submission": "📝 Feedback forms can be submitted online or offline.",
    "helpdesk": "☎️ Helpdesk is active during admission and exam season.",
    "erp_login_help": "💻 Contact IT support for ERP login issues.",
    "student_strength": "👥 The college has over 4000 students enrolled.",
    "campus_area": "🗺️ The campus is spread over approximately 10 acres.",
    "result_declaration": "📢 Results are declared on the HPU website within 2 months of exams.",
    "exam_rules": "📝 Students must carry ID proof and admit card for exams.",
    "classroom_facilities": "🏫 Classrooms are spacious and equipped with projectors in some blocks.",
    "attendance_portal": "📊 Attendance is maintained by class teachers and updated regularly.",
    "career_guidance": "💼 Career counseling sessions are held by the placement cell.",
    "skill_courses": "🖊️ Add-on skill courses like Spoken English are offered.",
    "language_lab": "🎧 A language lab helps improve spoken English and grammar.",
    "disciplinary_committee": "⚖️ The disciplinary committee ensures proper conduct.",
    "ragging_helpline": "☎️ Anti-ragging helpline number is displayed on notice boards.",
    "erp_training": "💻 ERP usage training is given at the beginning of session.",
    "canteen_special_items": "🍲 Popular canteen items include samosas, rajma-chawal, and tea.",
    "photocopy_shop": "📠 Photocopy facility is available near the library.",
    "blood_donation_camp": "🩸 Blood donation camps are organized annually by NSS.",
    "tree_plantation": "🌳 Tree plantation drives are organized on Environment Day.",
    "lost_and_found": "🔍 Lost and found section is managed by the admin office.",
    "principal_contact": "👨‍💼 You can meet the principal during official hours.",
    "exam_fees_submission": "💰 Exam fees are paid online or at the office counter.",
    "id_card_rules": "🆔 Carry your college ID card at all times inside campus.",
    "sports_events": "⚽ Inter-college sports tournaments are organized yearly.",
    "annual_day": "🎉 Annual Day includes cultural programs, awards, and performances.",
    "ncc_camps": "🚩 NCC cadets attend state and national-level training camps.",
    "student_awards": "🏆 Awards are given to toppers and best performers on Annual Day.",
    "seminar_registration": "🎤 Students can register for seminars via their departments.",
    "remedial_classes": "📚 Remedial classes are conducted for weaker students.",
    "holiday_notice": "📌 Holiday notices are posted on notice boards and website.",
    "erp_password_reset": "🔑 For ERP password reset, contact the IT department.",
    "canteen_opening_hours": "🕘 The canteen is open during college hours, till 3 PM.",
    "canteen_hygiene": "🧼 The canteen maintains proper hygiene and cleanliness.",
    "canteen_payment": "💳 You can pay in cash or UPI in the canteen.",
    "canteen_menu_display": "📋 The canteen menu is displayed daily at the counter.",
    "sports_registration": "🏅 Register for sports activities at the sports office.",
    "library_membership": "📚 Library membership is automatic after admission.",
    "library_rules": "🔖 Maintain silence in the library and return books on time.",
    "library_fine": "💰 A fine is charged for late return of library books.",
    "exam_admit_card": "🎫 Admit cards are distributed before exams by the exam cell.",
    "exam_duration": "⏳ Each exam paper is usually 3 hours long.",
    "exam_center": "🏫 Exam centers are usually within the college campus.",
    "marksheet_collection": "📜 Collect mark sheets from the college office after result declaration.",
    "internal_assessment": "📊 Internal marks are based on assignments, attendance, and class tests.",
    "attendance_shortage": "⚠️ Students below 75% attendance cannot appear in finals.",
    "student_feedback_system": "📝 Anonymous student feedback is collected every semester.",
    "alumni_association": "🤝 The Alumni Association organizes annual meets and mentoring sessions.",
    "college_website_help": "🌐 Visit https://gpgcuna.ac.in for updates, notices, and forms.",
    "placement_fairs": "💼 Placement fairs are occasionally organized with nearby colleges.",
    "soft_skills_training": "🗣️ Soft skills training like interview prep is conducted for final-year students.",
    "gender_cell": "👩 The Women Cell organizes awareness and safety programs.",
    "minority_cell": "🕌 Minority Cell provides support to minority students.",
    "sc_st_cell": "🧾 SC/ST Cell provides guidance and scholarship information.",
    "environmental_club": "🌱 Students can join the Environmental Club to promote eco-initiatives.",
    "youth_club": "🎶 Youth Club organizes cultural and social activities.",
    "magazine_submission_date": "📰 Check notice board for annual magazine submission deadlines.",
    "erp_login_issue": "💻 For ERP login issues, contact IT support staff.",
    "id_card_replacement": "🆔 Duplicate ID cards are issued with a small replacement fee.",
    "helpdesk_timings": "🕘 Helpdesk is active from 9:30 AM to 4:00 PM on working days.",
    "pta_contact": "📞 Parents can contact the PTA coordinator for academic concerns.",
    "medical_emergency": "🚑 In medical emergencies, report to the nearest faculty immediately.",
    "common_room_facility": "👩 A separate common room for girls is available.",
    "discipline_violation": "⚖️ Misconduct may lead to strict disciplinary action.",
    "lost_item_reporting": "📌 Report lost items at the admin office or security desk.",
    "notices_location": "📌 All important updates are available on the main notice board.",
    "online_classes_platform": "💻 Online classes are conducted via Google Meet or Zoom.",
    "holiday_information": "📅 Holiday list is provided in the academic calendar.",
    "career_counseling_sessions": "💼 Career counseling is conducted by trained professionals.",
    "lab_rules": "🔬 Lab coats and attendance are mandatory in science labs.",
    "practical_exam": "🧪 Practical exams are held before theory exams each semester.",
    "convocation_ceremony": "🎓 Convocation is held to distribute degrees after course completion.",
    "transfer_process": "📄 Apply for a transfer certificate through the college office.",
    "student_union_elections": "🗳️ Student union elections are held annually.",
    "fest_celebration": "🎊 Sanskriti Mahotsav is the main cultural festival of the college.",
    "canteen_special_days": "🍛 Special items are served on Fridays and Saturdays.",
    "wifi_issue": "📶 Report Wi-Fi connectivity issues to the IT cell.",
    "sports_equipment": "🏏 Sports equipment can be borrowed from the sports office.",
    "photocopy_facility": "📠 Photocopy and printout services are available near the library.",
    "study_material": "📚 Extra study material is provided by departments if required.",
    "result_inquiry": "📢 Check your results on the HPU website using your roll number.",
    "exam_fee_deadline": "💰 Submit exam fees before the deadline to avoid fines.",
    "discipline_guidelines": "📘 College rules must be followed to maintain discipline.",
    "cultural_event_registration": "🎤 Register for cultural events at the cultural committee desk.",
    "faculty_consultation": "👩‍🏫 Meet faculty during office hours for academic queries.",
    "scholarship_portal_help": "🌐 Apply for scholarships at https://scholarships.gov.in.",
    "canteen_seating": "🍴 Seating arrangement is available inside the canteen.",
    "sports_day": "🏆 Annual Sports Day is organized with multiple competitions.",
    "book_issue_limit": "📚 Students can issue up to 3 books at a time from the library.",
    "grievance_box": "📩 Grievance box is placed near the office for student complaints.",
    "cultural_committee": "🎭 Cultural committee organizes annual fests and competitions.",
    "attendance_inquiry": "📊 Attendance details are available with your class teacher.",
    "environment_awareness_drive": "🌏 Environment Day drives include rallies and tree plantation.",
    "blood_donation_drive": "🩸 NSS organizes blood donation drives annually.",
    "sports_practice": "🏃 Sports practice sessions are held every morning and evening.",
    "academic_calendar": "📅 The academic calendar is uploaded on the college website.",
    "canteen_closing_time": "⏰ The canteen closes after 3:00 PM daily.",
    "admission_helpdesk": "📝 Admission helpdesk is available during admission season.",
    "erp_training_sessions": "💻 ERP training is provided to students after admission.",
    "disciplinary_helpline": "☎️ Report indiscipline at the disciplinary helpline number.",
    "alumni_meet": "🎉 Annual Alumni Meet is organized to connect ex-students with current batches.",
    "student_corner_updates": "📌 Check the Students Corner section for forms and updates.",
    "canteen_menu": "🍜 Today's canteen menu is displayed at the counter every morning.",
    "canteen_feedback": "📝 You can give canteen feedback at the office suggestion box.",
    "sports_facility_timings": "🏟️ Sports ground is open from 7 AM to 6 PM daily.",
    "lab_facilities": "🔬 Labs for Physics, Chemistry, Biology, and Computer Science are available.",
    "computer_lab_timings": "💻 The computer lab is open from 10 AM to 4 PM.",
    "college_magazine_submission": "📰 Submit your articles to the editorial committee by the given deadline.",
    "student_union": "🗳️ A student union is elected annually to represent student interests.",
    "ragging_policy": "🚫 Ragging is banned as per Supreme Court guidelines. Report immediately if witnessed.",
    "student_corner": "📌 Students Corner section on the website provides forms and notices.",
    "financial_aid": "💸 Apply for financial aid in the office with supporting documents.",
    "bridge_courses": "📖 Bridge courses help new students adapt to college-level studies.",
    "iqac": "📊 Internal Quality Assurance Cell maintains academic quality standards.",
    "pta_meetings": "👪 PTA meetings are organized regularly for academic discussions.",
    "medical_facility": "🏥 First-aid facility is available; hospital is nearby.",
    "grievance_redressal": "📩 Drop your complaints in the grievance box or contact the grievance cell.",
    "youth_festival": "🎶 College participates in HPU Youth Festival every year.",
    "rainwater_initiative": "💧 Rainwater harvesting is part of the eco-friendly initiatives.",
    "environment_awareness": "🌱 Environmental awareness programs are held regularly.",
    "discipline_rules": "⚖️ Mobile phones are not allowed during class hours.",
    "holiday_list": "📅 The holiday list is included in the academic calendar.",
    "transfer_certificate": "📜 Apply in the office for a transfer certificate.",
    "migration_process": "📄 Migration certificates are issued after course completion.",
    "lost_id_process": "🆔 Apply for duplicate ID in the office with a fine.",
    "feedback_submission": "📝 Feedback forms can be submitted online or offline.",
    "helpdesk": "☎️ Helpdesk is active during admission and exam season.",
    "erp_login_help": "💻 Contact IT support for ERP login issues.",
    "student_strength": "👥 The college has over 4000 students enrolled.",
    "campus_area": "🗺️ The campus is spread over approximately 10 acres.",
    "result_declaration": "📢 Results are declared on the HPU website within 2 months of exams.",
    "exam_rules": "📝 Students must carry ID proof and admit card for exams.",
    "classroom_facilities": "🏫 Classrooms are spacious and equipped with projectors in some blocks.",
    "attendance_portal": "📊 Attendance is maintained by class teachers and updated regularly.",
    "career_guidance": "💼 Career counseling sessions are held by the placement cell.",
    "skill_courses": "🖊️ Add-on skill courses like Spoken English are offered.",
    "language_lab": "🎧 A language lab helps improve spoken English and grammar.",
    "disciplinary_committee": "⚖️ The disciplinary committee ensures proper conduct.",
    "ragging_helpline": "☎️ Anti-ragging helpline number is displayed on notice boards.",
    "erp_training": "💻 ERP usage training is given at the beginning of session.",
    "canteen_special_items": "🍲 Popular canteen items include samosas, rajma-chawal, and tea.",
    "photocopy_shop": "📠 Photocopy facility is available near the library.",
    "blood_donation_camp": "🩸 Blood donation camps are organized annually by NSS.",
    "tree_plantation": "🌳 Tree plantation drives are organized on Environment Day.",
    "lost_and_found": "🔍 Lost and found section is managed by the admin office.",
    "principal_contact": "👨‍💼 You can meet the principal during official hours.",
    "exam_fees_submission": "💰 Exam fees are paid online or at the office counter.",
    "id_card_rules": "🆔 Carry your college ID card at all times inside campus.",
    "sports_events": "⚽ Inter-college sports tournaments are organized yearly.",
    "annual_day": "🎉 Annual Day includes cultural programs, awards, and performances.",
    "ncc_camps": "🚩 NCC cadets attend state and national-level training camps.",
    "student_awards": "🏆 Awards are given to toppers and best performers on Annual Day.",
    "seminar_registration": "🎤 Students can register for seminars via their departments.",
    "remedial_classes": "📚 Remedial classes are conducted for weaker students.",
    "holiday_notice": "📌 Holiday notices are posted on notice boards and website.",
    "erp_password_reset": "🔑 For ERP password reset, contact the IT department.",
    "canteen_opening_hours": "🕘 The canteen is open during college hours, till 3 PM."
})
